services:
  jj-db:
    image: postgres:17-alpine
    container_name: jj-banking-db
    restart: always
    environment:
      POSTGRES_DB: jjbanking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - jj-data:/var/lib/postgresql/data

  jj-api:
    build: .
    container_name: jj-banking-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=jj-db;Database=jjbanking_db;Username=admin;Password=password123
    depends_on:
      - jj-db

volumes:
  jj-data: