services:
  jj-api:
    build: .
    container_name: jjbanking-api
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # O caminho do banco deve apontar para a pasta que vamos persistir no volume
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/jjbanking.db
    volumes:
      - jj-banking-data:/app/data
    deploy:
      resources:
        limits:
          memory: 128M # Limite de segurança para sua VPS de 512MB

volumes:
  jj-banking-data: